### ISSUE TITLE
[Bug]: Solar template doesn't work with Dark Mode (tailwind v4)

### ISSUE THREAD

**Issue by bdiazc90** [tremorlabs/tremor#111]
### Link to minimal reproduction

https://flatrepo.vercel.app

### Steps to reproduce

this is mi layout.tsx:

```tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.className} min-h-screen overflow-x-hidden scroll-auto bg-gray-50 antialiased selection:bg-teal-100 selection:text-teal-600 dark:bg-slate-950`}
      >
        <ThemeProvider
          defaultTheme="system"
          attribute="class"
          disableTransitionOnChange
          enableSystem
          storageKey="theme-preference"
        >
          <NavBar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
```

This is my globals.css (using tailwind 4)
```css
@import "tailwindcss";

@theme {
  --color-primary-50: oklch(0.984 0.019 168);
  --color-primary-100: oklch(0.956 0.045 168);
  --color-primary-200: oklch(0.917 0.08 168);
  --color-primary-300: oklch(0.865 0.127 168);
  --color-primary-400: oklch(0.789 0.154 168);
  --color-primary-500: oklch(0.715 0.143 168);
  --color-primary-600: oklch(0.609 0.126 168);
  --color-primary-700: oklch(0.52 0.105 168);
  --color-primary-800: oklch(0.45 0.085 168);
  --color-primary-900: oklch(0.398 0.07 168);
  --color-primary-950: oklch(0.302 0.056 168);

  --animate-hide: hide 150ms cubic-bezier(0.16, 1, 0.3, 1);
  --animate-slide-down-and-fade: slideDownAndFade 150ms
    cubic-bezier(0.16, 1, 0.3, 1);
  --animate-slide-left-and-fade: slideLeftAndFade 150ms
    cubic-bezier(0.16, 1, 0.3, 1);
  --animate-slide-up-and-fade: slideUpAndFade 150ms
    cubic-bezier(0.16, 1, 0.3, 1);
  --animate-slide-right-and-fade: slideRightAndFade 150ms
    cubic-bezier(0.16, 1, 0.3, 1);
  --animate-accordion-open: accordionOpen 150ms cubic-bezier(0.87, 0, 0.13, 1);
  --animate-accordion-close: accordionClose 150ms cubic-bezier(0.87, 0, 0.13, 1);
  --animate-dialog-overlay-show: dialogOverlayShow 150ms
    cubic-bezier(0.16, 1, 0.3, 1);
  --animate-dialog-content-show: dialogContentShow 150ms
    cubic-bezier(0.16, 1, 0.3, 1);
  --animate-drawer-slide-left-and-fade: drawerSlideLeftAndFade 150ms
    cubic-bezier(0.16, 1, 0.3, 1);
  --animate-drawer-slide-right-and-fade: drawerSlideRightAndFade 150ms ease-in;
  --animate-dashes: dashes 0.8s linear infinite;
  --animate-dashes-reverse: dashes 0.8s linear infinite reverse;
  --animate-hover: hover 4s cubic-bezier(0.45, 0, 0.55, 1) infinite;

  @keyframes hide {
    from {
      opacity: 1;
    }
    to {
      opacity: 0;
    }
  }
  @keyframes slideDownAndFade {
    from {
      opacity: 0;
      transform: translateY(-6px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
  @keyframes slideLeftAndFade {
    from {
      opacity: 0;
      transform: translateX(6px);
    }
    to {
      opacity: 1;
      transform: translateX(0);
    }
  }
  @keyframes slideUpAndFade {
    from {
      opacity: 0;
      transform: translateY(6px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
  @keyframes slideRightAndFade {
    from {
      opacity: 0;
      transform: translateX(-6px);
    }
    to {
      opacity: 1;
      transform: translateX(0);
    }
  }
  @keyframes accordionOpen {
    from {
      height: 0px;
    }
    to {
      height: var(--radix-accordion-content-height);
    }
  }
  @keyframes accordionClose {
    from {
      height: var(--radix-accordion-content-height);
    }
    to {
      height: 0px;
    }
  }
  @keyframes dialogOverlayShow {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }
  @keyframes dialogContentShow {
    from {
      opacity: 0;
      transform: translate(-50%, -45%) scale(0.95);
    }
    to {
      opacity: 1;
      transform: translate(-50%, -50%) scale(1);
    }
  }
  @keyframes drawerSlideLeftAndFade {
    from {
      opacity: 0;
      transform: translateX(100%);
    }
    to {
      opacity: 1;
      transform: translateX(0);
    }
  }
  @keyframes drawerSlideRightAndFade {
    from {
      opacity: 1;
      transform: translateX(0);
    }
    to {
      opacity: 0;
      transform: translateX(100%);
    }
  }
  @keyframes dashes {
    0% {
      stroke-dashoffset: -7;
    }
    100% {
      stroke-dashoffset: 0;
    }
  }
  @keyframes hover {
    0%,
    100% {
      transform: translateY(0);
    }
    50% {
      transform: translateY(-10px);
    }
  }
}

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }

  :root {
    --background: oklch(0.98 0 0);
    --foreground: oklch(0.25 0 0);
  }

  .dark {
    --background: oklch(0.25 0 0);
    --foreground: oklch(0.98 0 0);
  }

  body {
    background-color: oklch(var(--background));
    color: oklch(var(--foreground));
  }
}

.mask {
  mask-image: radial-gradient(rgba(0, 0, 0, 0.7) 0%, transparent 70%);
}

@keyframes gridMovingLine {
  0% {
    transform: translateX(100%);
    opacity: 0;
  }
  20% {
    opacity: 100;
  }
  100% {
    transform: translateX(-100%);
    opacity: 100;
  }
}

.neon-border {
  position: relative;
}

.neon-border::before {
  content: "";
  position: absolute;
  inset: 0;
  border-radius: inherit;
  padding: 0.8px;
  background: linear-gradient(
    90deg,
    oklch(75% 0.15 60 / 0.8),
    oklch(55% 0.2 320 / 0.8),
    var(--color-primary-500),
    oklch(70% 0.15 195 / 0.8),
    oklch(85% 0.15 85 / 0.8)
  );
  background-size: 200% 200%;
  animation: neonShift 2s linear infinite;

  pointer-events: none;

  -webkit-mask:
    linear-gradient(#fff 0 0) content-box,
    linear-gradient(#fff 0 0) border-box;
  mask:
    linear-gradient(#fff 0 0) content-box,
    linear-gradient(#fff 0 0) border-box;
  -webkit-mask-composite: xor;
  mask-composite: exclude;
}

@keyframes neonShift {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 200% 50%;
  }
}
```

### What is expected?

To change the theme colors using next-themes with ThemeProvider

### What is actually happening?

The colors only follows the system theme
